using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TigerCompiler.Parsing
{
    public enum Tokens
    {
        ALIAS_TYPE = 4,
        AND = 5,
        ARRAY = 6,
        ARRAY_EXPR = 7,
        ARRAY_TYPE = 8,
        ASSIGN = 9,
        BREAK = 10,
        COLON = 11,
        COMMA = 12,
        DECLARATIONS = 13,
        DEC_FUNCTIONS = 14,
        DEC_TYPES = 15,
        DEC_VARS = 16,
        DIGIT = 17,
        DIV = 18,
        DO = 19,
        ELSE = 20,
        END = 21,
        EQ = 22,
        ESC = 23,
        EXPRESSIONS = 24,
        FIELD_TYPE = 25,
        FIELD_VALUE = 26,
        FOR = 27,
        FUNCALL = 28,
        FUNCTION = 29,
        FUNDEC = 30,
        GETHAN = 31,
        GTHAN = 32,
        ID = 33,
        IF = 34,
        IN = 35,
        INT = 36,
        LCB = 37,
        LET = 38,
        LETHAN = 39,
        LETINEND = 40,
        LETTER = 41,
        LP = 42,
        LSB = 43,
        LTHAN = 44,
        MINUS = 45,
        ML_COMMENTS = 46,
        NEGATIVE = 47,
        NIL = 48,
        NOTEQ = 49,
        OF = 50,
        OR = 51,
        PCHAR = 52,
        PERIOD = 53,
        PLUS = 54,
        PROGRAM = 55,
        RCB = 56,
        RECORD = 57,
        RECORD_TYPE = 58,
        RP = 59,
        RSB = 60,
        SEMI = 61,
        STAR = 62,
        STRING = 63,
        THEN = 64,
        TO = 65,
        TYPE = 66,
        TYPE_DECLARATION = 67,
        USCORE = 68,
        VAR = 69,
        VARDEC = 70,
        WHILE = 71,
        WS = 72,
    }
}
